[book]
title = "Wiki"
description = "Wiki"
authors = ["Aidanbek Kalymbekov"]
language = "ru"


[output.html]
mathjax-support = true
site-url = "/book/"
git-repository-url = "https://github.com/aidanbek/wiki"
